import { StrictMode, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { ApiClient, MXRayEvidence, MXRayJob, RunnerFixture, RunnerJob } from "./api";
import "./styles.css";

const api = new ApiClient(import.meta.env.VITE_DFIRWB_API_URL ?? window.location.origin);

function App() {
  const [fixtures, setFixtures] = useState<RunnerFixture[]>([]);
  const [selected, setSelected] = useState("");
  const [job, setJob] = useState<RunnerJob | null>(null);
  const [notice, setNotice] = useState("Loading synthetic fixture catalog…");
  const [email, setEmail] = useState<MXRayEvidence | null>(null);
  const [mxray, setMxray] = useState<MXRayJob | null>(null);
  const selectedFixture = useMemo(() => fixtures.find((fixture) => fixture.fixture_id === selected), [fixtures, selected]);

  useEffect(() => {
    api.runnerCatalog().then((data) => {
      setFixtures(data.fixtures);
      setSelected(data.fixtures[0]?.fixture_id ?? "");
      setNotice("Synthetic dev context · tenant scope is server-enforced");
    }).catch((error: Error) => setNotice(error.message));
    api.mxrayEvidence().then((data) => setEmail(data.items[0] ?? null)).catch((error: Error) => setNotice(error.message));
  }, []);

  async function register() {
    if (!selected) return;
    await api.runnerRegister(selected);
    setNotice(`Registered ${selected} with provenance hash from the verified corpus manifest.`);
  }

  async function submit() {
    if (!selected) return;
    setNotice("Processing through the evidence-safe staging workflow…");
    setJob(await api.runnerSubmit(selected));
    setNotice("Processing complete; analyst review is required before approval.");
  }

  async function review(decision: "approve" | "quarantine") {
    if (!job) return;
    setJob(await api.runnerReview(job.job_id, decision));
    setNotice(decision === "approve" ? "Approved by analyst review gate." : "Quarantined; no result was applied.");
  }

  async function teardown() {
    const result = await api.runnerTeardown();
    setJob(null);
    setNotice(`${String(result.status)} · synthetic workspace removed safely`);
  }

  async function analyzeEmail() {
    if (!email) return;
    setNotice("MXRay is parsing metadata locally; raw evidence stays server-side…");
    setMxray(await api.mxrayAnalyze(email.evidence_id));
    setNotice("MXRay result ready. Analyst approval is required before report use.");
  }

  async function reviewEmail(decision: "approve" | "quarantine") {
    if (!mxray) return;
    setMxray(await api.mxrayReview(mxray.job_id, decision));
    setNotice(decision === "approve" ? "MXRay findings approved for case-report use." : "MXRay result quarantined; no findings applied.");
  }

  return (
    <main>
      <header className="topbar"><div><p className="eyebrow">DFIR Evidence Workbench</p><h1>Analyst runner</h1></div><span className="dev-badge">DEV ONLY · SYNTHETIC</span></header>
      <p className="lede">Stage, process, inspect, and review generated evidence without mounting or mutating a source. Every action below uses the local API seam; the browser never selects tenant scope.</p>
      <section className="panel workflow" aria-label="Evidence workflow">
        <div className="step"><span>01</span><div><strong>Select fixture</strong><label htmlFor="fixture">Verified corpus member</label><select id="fixture" value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">Choose fixture…</option>{fixtures.map((fixture) => <option key={fixture.fixture_id} value={fixture.fixture_id}>{fixture.fixture_id} · {fixture.class}</option>)}</select></div></div>
        <div className="fixture-meta">{selectedFixture ? <><b>{selectedFixture.scenario.join(", ")}</b><span>{selectedFixture.format}</span><span>CC0 generated bytes</span></> : "No fixture selected"}</div>
        <div className="actions"><button type="button" onClick={register} disabled={!selected}>Register evidence</button><button type="button" className="primary" onClick={submit} disabled={!selected}>Submit processing</button></div>
      </section>
      <section className="panel workflow" aria-label="MXRay email analysis"><div><p className="eyebrow">Email evidence</p><h2>{email?.subject ?? "Loading staged email…"}</h2><p className="lede">{email ? `${email.media_type.toUpperCase()} · ${email.size_bytes} bytes · SHA-256 ${email.sha256}` : "No staged email evidence"}</p></div><div className="actions"><button type="button" className="primary" onClick={analyzeEmail} disabled={!email}>Analyze with MXRay</button></div></section>
      {mxray && <section className="panel result" aria-live="polite"><div className="result-head"><div><p className="eyebrow">MXRay result</p><h2>{mxray.job_id}</h2></div><span className={`status ${mxray.status}`}>{mxray.status.replace(/_/g, " ")}</span></div><div className="facts"><div><small>Findings</small><strong>{mxray.result.findings?.length ?? 0}</strong></div><div><small>Attachments</small><strong>{mxray.result.attachments?.length ?? 0}</strong></div><div><small>External enrichment</small><strong>{mxray.result.audit?.egress ?? "none"}</strong></div></div><details open><summary>Analyst findings and provenance</summary><pre>{JSON.stringify({message: mxray.result.message, findings: mxray.result.findings, attachments: mxray.result.attachments, capabilities: mxray.result.capabilities, toolchain: mxray.result.toolchain, limitations: mxray.result.limitations, provenance: mxray.result.provenance, reports: mxray.result.reports, safe_html: mxray.result.safe_html}, null, 2)}</pre></details>{mxray.status === "ready_for_review" && <div className="review"><strong>Case-report approval gate</strong><span>Approval is required; raw message content is never returned to the browser.</span><div><button type="button" onClick={() => reviewEmail("quarantine")}>Quarantine</button><button type="button" className="primary" onClick={() => reviewEmail("approve")}>Approve findings</button></div></div>}</section>}
      {job && <section className="panel result" aria-live="polite"><div className="result-head"><div><p className="eyebrow">Processing job</p><h2>{job.job_id}</h2></div><span className={`status ${job.status}`}>{job.status.replace(/_/g, " ")}</span></div><div className="progress"><span style={{ width: `${job.progress}%` }} /></div><div className="facts"><div><small>Fixture</small><strong>{job.fixture_id}</strong></div><div><small>Attempt</small><strong>{job.attempt}</strong></div><div><small>Progress</small><strong>{job.progress}%</strong></div></div>{job.provenance && <details><summary>Provenance / manifest</summary><pre>{JSON.stringify(job.provenance, null, 2)}</pre></details>}{job.result && <details open><summary>Output inspection</summary><pre>{JSON.stringify(job.result, null, 2)}</pre></details>}{job.status === "ready_for_review" && <div className="review"><strong>Analyst review gate</strong><span>Do not apply findings automatically.</span><div><button type="button" onClick={() => review("quarantine")}>Quarantine</button><button type="button" className="primary" onClick={() => review("approve")}>Approve result</button></div></div>}</section>}
      <footer><span>{notice}</span><button type="button" className="danger" onClick={teardown}>Safe teardown</button></footer>
    </main>
  );
}

createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
